# Generated by Django 5.0.1 on 2024-02-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_scrapdata_tag_alter_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(max_length=500, unique=True),
        ),
    ]
